FROM grafana/grafana:latest

# Copy datasource and dashboard configuration files
# COPY provisioning /etc/grafana/provisioning

# Environment variables to disable authentication
ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
ENV GF_SECURITY_ADMIN_USER=admin
ENV GF_SECURITY_ADMIN_PASSWORD=admin
